# Generated by Django 6.0.3 on 2026-03-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=True)),
                ('weekly_reports', models.BooleanField(default=True)),
            ],
        ),
    ]
