# Generated by Django 6.0.3 on 2026-03-14 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('color', models.CharField(default='#2563EB', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='students.student')),
            ],
        ),
    ]
