# Generated by Django 6.0.3 on 2026-03-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Late', 'Late')], default='Submitted', max_length=20),
        ),
    ]
