# Generated by Django 6.0.3 on 2026-03-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_assignmentsubmission_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
