# Generated by Django 6.0.3 on 2026-03-17 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='faculty',
            field=models.ManyToManyField(blank=True, to='students.faculty'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.faculty'),
        ),
    ]
