# Generated by Django 6.0.3 on 2026-03-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_assignment_faculty_alter_assignment_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty')], default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
    ]
