# Generated by Django 6.0.3 on 2026-03-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_assignment_course_assignment_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submitted_by',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
