# Generated by Django 6.0.3 on 2026-03-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_enrollment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'course', 'date')},
        ),
    ]
