# Generated by Django 6.0.3 on 2026-03-20 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_assignment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.faculty'),
        ),
    ]
