# Generated by Django 6.0.3 on 2026-03-21 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_assignmentsubmission_faculty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='courses',
            field=models.ManyToManyField(blank=True, to='students.course'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_broadcast',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
